linters:
  ErbSafety:
    # TODO: [@rhymes] re-enable this and fix the violations,
    # see https://github.com/Shopify/erb-lint#ErbSafety
    enabled: false
  SelfClosingTag:
    enabled: false
  ParserErrors:
    exclude:
      - '**/app/views/pages/_editor_guide_text.html.erb'
  SpaceInHtmlTag:
    exclude:
      - '**/app/views/pages/_editor_guide_text.html.erb'
  AllowedScriptType:
    enabled: true
    allowed_types:
      - 'text/javascript'
      - 'text/x-tmpl'
      - 'application/ld+json'
    allow_blank: true
    disallow_inline_scripts: false
  Rubocop:
    enabled: true
    rubocop_config:
      require: standard
      inherit_gem:
        standard: config/base.yml
      Layout/TrailingEmptyLines:
        Enabled: false
      Layout/InitialIndentation:
        Enabled: false
      Lint/UselessAssignment:
        Enabled: false
      AllCops:
        DisabledByDefault: true
