require:
  - standard
  - rubocop-performance
  - rubocop-rails
  - rubocop-rspec

inherit_gem:
  standard: config/base.yml

AllCops:
  Exclude:
    - bin/**/*
    - db/schema.rb
    - db/migrate/*.rb
    - node_modules/**/*
    - tmp/**/*
    - vendor/**/*
    - .pryrc
  DisplayStyleGuide: true
  ExtraDetails: true

Rails:
  Enabled: true # enable rubocop-rails cops
RSpec:
  Enabled: true # enable rubocop-rspec cops
Performance:
  Enabled: true
