ignore:
  - "vendor"
  - "bin"
  - "**/*.svg"
  - "lib/sitemap_generator"
  - "lib/generators"
  - "app/assets/javascripts"
flag_management:
  default_rules:
    statuses:
      - type: project
        target: auto
        threshold: 1%
