version: "3"

x-uffizzi:
  ingress:
    service: rails
    port: 3000

services:
  rails:
    image: "${APP_IMAGE}"
    container_name: forem_rails
    ports:
      - "3000:3000"
    depends_on:
      - db
      - redis
    healthcheck:
      test: ["CMD", "curl" , "-f", "http://localhost:3000/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
    environment:
      RAILS_ENV: development
      DATABASE_URL: postgresql://forem:forem@localhost:5432/PracticalDeveloper_development
      REDIS_SESSIONS_URL: redis://localhost:6379
      REDIS_SIDEKIQ_URL: redis://localhost:6379
      REDIS_URL: redis://localhost:6379
      RACK_TIMEOUT_WAIT_TIMEOUT: 10000
      RACK_TIMEOUT_SERVICE_TIMEOUT: 10000
      STATEMENT_TIMEOUT: 10000
      APP_DOMAIN: localhost:3000
      APP_PROTOCOL: https://
    entrypoint: ["dockerize", "-wait", "tcp://localhost:5432", "-wait", "tcp://localhost:6379", "-wait", "file:///opt/apps/forem/vendor/bundle/.bundle_finished", "-timeout", "5400s"]
    command: [ "bash", "-c", "./uffizzi/entrypoint.sh bootstrap"]
    deploy:
      resources:
        limits:
          memory: 4000M

  sidekiq:
    image: "${APP_IMAGE}"
    container_name: forem_sidekiq
    depends_on:
      rails:
        condition: service_healthy
      redis:
        condition: service_healthy
      db:
        condition: service_healthy
    environment:
      RAILS_ENV: development
      REDIS_SESSIONS_URL: redis://localhost:6379
      REDIS_SIDEKIQ_URL: redis://localhost:6379
      REDIS_URL: redis://localhost:6379
      DATABASE_URL: postgresql://forem:forem@localhost:5432/PracticalDeveloper_development
    command: ["bundle", "exec", "sidekiq","-c","2"]
    deploy:
      resources:
        limits:
          memory: 500M

  db:
    image: postgres:11-alpine
    container_name: forem_postgresql
    healthcheck:
      test: [ "CMD", "pg_isready", "-d" ,"forem", "-U", "forem" ]
      interval: 10s
      timeout: 5s
      retries: 5
    environment:
      POSTGRES_USER: forem
      POSTGRES_PASSWORD: forem
      POSTGRES_DB: PracticalDeveloper_development
    ports:
      - "5432:5432"

  redis:
    image: redis:6.0.9-alpine
    container_name: forem_redis
    healthcheck:
      test: [ "CMD", "redis-cli", "--raw", "incr", "ping" ]
      interval: 20s
      timeout: 5s
      retries: 3
      start_period: 10s
    ports:
      - "6379:6379"
